### ISSUE TITLE
Better HTTP OPTIONS handling

### ISSUE THREAD

**Issue by pferretti** [contactlab/saray#2]
Now, by default, all `HTTP OPTIONS` responses returns an `HTTP 200` status code.
We need to be more precise, so the stubber should return a 200 status code for an `OPTIONS `call on an existing resource and a 404 for an `OPTIONS `call on a not existing resource.

**Comment by tsriram** [comment]
I'll take this up!

**Comment by pferretti** [comment]
Ok, you can send a PR on the develop branch!
