### ISSUE TITLE
`yarn add` or `yarn install` failing on windows

### ISSUE THREAD

**Issue by Slumber86** [contactlab/saray#80]
Trying to install Saray on a windows machine with yarn we are getting this error
: 
```$ yarn add saray
yarn add v0.24.6
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/saray/-/saray-1.7.1.tgz: ENOENT: no such file or directory, open 'C:\\Users\\user\\AppData\\Local\\Yarn\\cache\\v1\\npm-saray-1.7.1-6b9fee1faceefedbb74ccbb3affa4a5a243595b2\\test\\data\\call4?param1=value1.POST.js'".
info If you think this is a bug, please open a bug report with the information provided in "D:\\prova\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

ENVIRONMENT:
Node 7
Yarn 0.24.7
Windows 10 or Windows Server 2012 R2

**Comment by pferretti** [comment]
Unfortunately it's a known issue.
The main problem is that NTFS doesn't support some "special" characters, like "?", in paths. So, data stubs that are handled without problems under Linux and MacOS are impossible to manage under Windows. For example a path like `test/data/call4?param1=value1.POST.js` and unfortunately all of the data stubs paths used for the Saray test suite.

There is a resolved issue (https://github.com/contactlab/saray/issues/67) that introduced urlencoded paths for a complete support under Windows, but we haven't migrated the data stubs relative to the test suite to new urlencoded file names.
The main reason is that we think that the urlencoded workaround (that make stub paths more Windows-compatible) leads to a file naming hell.

The easy part of Saray is that it's simple to create data stubs on-the-fly and, with urlencoded paths, something like `test/data/call4?param1=value1.POST.js` would became `test/data/call4%3Fparam1%3Dvalue1.POST.js`. This isn't simple and intuitive!

So, apart from the urlencoding of paths. we don't have a good solution for a complete compatibility with NTFS. Obviously, we are open to new ideas!

**Comment by Slumber86** [comment]
Thanks for the quick response, the thing that I don't understend is why yarn fails while NPM doesn't.
One solution can be to place the test folder in `.npmignore `

**Comment by pferretti** [comment]
On npm there's a patch release (1.7.2) trying to solve this issue using .npmignore. Thanks for the advice :-)

**Comment by Slumber86** [comment]
ok, i'll give a try and give you some feedback

**Comment by Slumber86** [comment]
Now works 💯

**Comment by Slumber86** [comment]
Seems that the install works, but now fails with npm on all platforms, while on windows doesn't find index.html, maybe you mistaken a build step?

**Comment by pferretti** [comment]
Ooops... I'll check and give you some feedback

**Comment by pferretti** [comment]
There was a mistake in package.json into the "bin" section. Now everything should be ok!
